

[[redirects]]
  from = "/blog/content-blog-*"
  to = "/blog/*"
  status = 301  


[[redirects]]
  from = "/contact/"
  to = "/kontakt/"
  status = 301  


[[redirects]]
  from = "/about/"
  to = "/istorija-kompanije/"
  status = 301  