

[[redirects]]
  from = "/blog/content-blog-*"
  to = "/blog/*"
  status = 301  


[[redirects]]
  from = "/contact/"
  to = "/kontakt/:splat"
  status = 301  


[[redirects]]
  from = "/about/"
  to = "/istorija-kompanije/:splat"
  status = 301  


[[redirects]]
  from = "/blog/2/"
  to = "/blog/:splat"
  status = 301  


[[redirects]]
  from = "/blog/3/"
  to = "/blog/:splat"
  status = 301  

  